/**
 * 场地列表
 */
const VenueList = [
  {
    id: 10,
    campusId: 2,
    campusName: null,
    name: '露天网球场',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/30c08b3ab9d145f2419341f6796dfe83abd63d9038d3af412a8adeaa0c67df38.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '华西校区西门',
    sliderPicUrls: null,
    leaderUser: '欧涛 13551094169;郭为 13881301676',
    phone: null,
    status: 0,
    qrId: 'C00035000019',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">教学预留：1~17周</span></p><table style="width: 100%;"><tbody><tr><th colSpan="1" rowSpan="1" width="auto">课程</th><th colSpan="1" rowSpan="1" width="auto">星期</th><th colSpan="1" rowSpan="1" width="auto">时间</th><th colSpan="1" rowSpan="1" width="auto">场地</th></tr><tr><td colSpan="1" rowSpan="1" width="auto">网球</td><td colSpan="1" rowSpan="1" width="auto">周一</td><td colSpan="1" rowSpan="1" width="auto">8:00-9:40</td><td colSpan="1" rowSpan="1" width="auto">全场2片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">网球</td><td colSpan="1" rowSpan="1" width="auto">周一</td><td colSpan="1" rowSpan="1" width="auto">10:00-11:40</td><td colSpan="1" rowSpan="1" width="auto">全场2片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">网球</td><td colSpan="1" rowSpan="1" width="auto">周四</td><td colSpan="1" rowSpan="1" width="auto">19:30-21:00</td><td colSpan="1" rowSpan="1" width="auto">全场2片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">网球</td><td colSpan="1" rowSpan="1" width="auto">周五</td><td colSpan="1" rowSpan="1" width="auto">10:00-11:40</td><td colSpan="1" rowSpan="1" width="auto">全场2片</td></tr></tbody></table><p><br></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742373871000,
    facilities: null,
    fields: null,
    campus: null,
  },
  {
    id: 9,
    campusId: 2,
    campusName: null,
    name: '华西羽毛球馆',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/30c08b3ab9d145f2419341f6796dfe83abd63d9038d3af412a8adeaa0c67df38.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '华西校区西门',
    sliderPicUrls: null,
    leaderUser: '吴家海 13982192798;吴朝志 13618030265',
    phone: null,
    status: 0,
    qrId: 'C00035000018',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="color: rgb(225, 60, 57); font-family: 宋体;"><strong>该场馆因贡嘎杯比赛暂时关闭</strong></span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742373871000,
    facilities: null,
    fields: null,
    campus: null,
  },
  {
    id: 5,
    campusId: 1,
    campusName: null,
    name: '乒乓球馆',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/30c08b3ab9d145f2419341f6796dfe83abd63d9038d3af412a8adeaa0c67df38.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '望江中心体育馆',
    sliderPicUrls: null,
    leaderUser: '谢善学 18980875322;李晨博 13350883095',
    phone: null,
    status: 0,
    qrId: 'C00035000009',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">教学预留：3月17日开始4~18周</span></p><table style="width: 100%;"><tbody><tr><th colspan="1" rowspan="1" width="auto" style="text-align: center;">课程</th><th colSpan="1" rowSpan="1" width="auto">星期</th><th colSpan="1" rowSpan="1" width="auto">时间</th><th colSpan="1" rowSpan="1" width="auto">场地</th></tr><tr><td colSpan="1" rowSpan="1" width="auto">乒乓球</td><td colSpan="1" rowSpan="1" width="auto">周二</td><td colSpan="1" rowSpan="1" width="auto">19:30-21:00</td><td colSpan="1" rowSpan="1" width="auto">全场12片</td></tr></tbody></table><p><br></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742373583000,
    facilities: null,
    fields: null,
    campus: null,
  },
  {
    id: 4,
    campusId: 1,
    campusName: null,
    name: '风雨羽毛球馆',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/30c08b3ab9d145f2419341f6796dfe83abd63d9038d3af412a8adeaa0c67df38.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '望江中心体育馆',
    sliderPicUrls: null,
    leaderUser: '谢善学 18980875322;李晨博 13350883095',
    phone: null,
    status: 0,
    qrId: 'C00035000008',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">教学预留：3月17日开始4~18周</span></p><table style="width: 100%;"><tbody><tr><th colSpan="1" rowSpan="1" width="auto">课程</th><th colSpan="1" rowSpan="1" width="auto">星期</th><th colSpan="1" rowSpan="1" width="auto">时间</th><th colSpan="1" rowSpan="1" width="auto">场地</th></tr><tr><td colSpan="1" rowSpan="1" width="auto">气排球</td><td colSpan="1" rowSpan="1" width="auto">周三</td><td colSpan="1" rowSpan="1" width="auto">19:00-20:30</td><td colSpan="1" rowSpan="1" width="auto">5-8号</td></tr></tbody></table><p><br></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742373479000,
    facilities: null,
    fields: null,
    campus: null,
  },
  {
    id: 3,
    campusId: 1,
    campusName: null,
    name: '东区红土网球场',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/fcddb437c187d62ecb06fa351eedcfc94a4c4522ad6f5c0b5c53679d111619c8.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '东区第三教学楼附近',
    sliderPicUrls: null,
    leaderUser: '黄庆忠 13438155359;邓秀兰 13438153550',
    phone: null,
    status: 0,
    qrId: 'C00035000011',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p><p style="text-indent: 28pt;"><br></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">教学预留：3月17日开始4~18周 </span></p><table style="width: 100%;"><tbody><tr><th colSpan="1" rowSpan="1" width="auto">课程</th><th colSpan="1" rowSpan="1" width="auto">星期</th><th colSpan="1" rowSpan="1" width="auto">时间</th><th colSpan="1" rowSpan="1" width="125">场地号</th></tr><tr><td colSpan="1" rowSpan="1" width="auto">网球</td><td colSpan="1" rowSpan="1" width="auto">周一</td><td colSpan="1" rowSpan="1" width="auto">18:30-20:00</td><td colSpan="1" rowSpan="1" width="auto">5-8号</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">网球</td><td colSpan="1" rowSpan="1" width="auto">周三</td><td colSpan="1" rowSpan="1" width="auto">14:00-16:35</td><td colSpan="1" rowSpan="1" width="auto">5-8号</td></tr></tbody></table><p style="text-indent: 28pt;"><br></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742029242000,
    facilities: null,
    fields: null,
    campus: null,
  },
  {
    id: 2,
    campusId: 1,
    campusName: null,
    name: '西区网球场',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/d7ef18ca95808b41dd2ecaa56a76feb1bf746595973eea38c88d8ef42a50ca0e.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '西区运动场',
    sliderPicUrls: null,
    leaderUser: '耿燕梅 15928144755;彭文云 13980423288',
    phone: null,
    status: 0,
    qrId: 'C00035000012',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742029242000,
    facilities: null,
    fields: null,
    campus: null,
  },
  {
    id: 1,
    campusId: 1,
    campusName: null,
    name: '二楼羽毛球馆',
    picUrl:
      'https://cgzx.scu.edu.cn/admin-api/infra/file/4/get/30c08b3ab9d145f2419341f6796dfe83abd63d9038d3af412a8adeaa0c67df38.jpg',
    introduce: '<p>--</p>',
    score: 5,
    type: 1,
    location: '望江中心体育馆',
    sliderPicUrls: null,
    leaderUser: '王金甫 13684014699;商加田 13880982088',
    phone: null,
    status: 0,
    qrId: 'C00035000007',
    venueNotice:
      '<p style="text-indent: 28pt;"><span style="font-family: 宋体;">四川大学收费运动场馆预约须知</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">1、 本系统当前为试运行阶段。每天早上8点30分开放预约当天的场地预约权限。华西和望江所有羽毛球和网球场9-10点场地免费，10点后可提供预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">2、单位时段为1小时，一天每人最多可预约连续的两个单位时段，同一时段每人只能预约1片场地。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">3、提交预约并完成支付后，预约成功。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">4、预约成功后，如因用户个人原因需取消订单，用户必须在距使用时间1小时之前取消订单退全款，否则不予退款；如遇学校原因及维修等特殊情况无法提供场地服务，由学校进行取消订单操作，全额退费。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">5、用户到达场馆后必须向场馆管理人员出示预约成功的真实信息和表明与预约信息相一致的身份信息，如校园卡等。如出现信息不一致，场馆管理人员有权按照用户真实身份要求补交差额，否则不允许使用场地。并对该账号封禁1个月，期间账号无法进行场地预约。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">6、室外网球场灯光使用需现场交纳相关费用。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">7、对于各种多次恶意定场、取消订单，扰乱预约活动正常进行，损害学校及其他参与人利益的账号，根据造成后果的严重程度实行封号1个月以上、永久封禁等处罚。</span></p><p style="text-indent: 28pt;"><span style="font-family: 宋体;">教学预留：3月17日开始4~18周</span></p><table style="width: 100%;"><tbody><tr><th colSpan="1" rowSpan="1" width="auto">课程</th><th colSpan="1" rowSpan="1" width="auto">星期</th><th colSpan="1" rowSpan="1" width="auto">时间</th><th colSpan="1" rowSpan="1" width="auto">场地</th></tr><tr><td colSpan="1" rowSpan="1" width="auto">羽毛球</td><td colSpan="1" rowSpan="1" width="auto">周一</td><td colSpan="1" rowSpan="1" width="auto">10:00-11:40</td><td colSpan="1" rowSpan="1" width="auto">全场10片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">羽毛球</td><td colSpan="1" rowSpan="1" width="auto">周一</td><td colSpan="1" rowSpan="1" width="auto">14:00-15:40</td><td colSpan="1" rowSpan="1" width="auto">全场10片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">羽毛球</td><td colSpan="1" rowSpan="1" width="auto">周二</td><td colSpan="1" rowSpan="1" width="auto">16:55-18:35</td><td colSpan="1" rowSpan="1" width="auto">全场10片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">羽毛球</td><td colSpan="1" rowSpan="1" width="auto">周三</td><td colSpan="1" rowSpan="1" width="auto">16:00-18:00</td><td colSpan="1" rowSpan="1" width="auto">全场10片</td></tr><tr><td colSpan="1" rowSpan="1" width="auto">羽毛球</td><td colSpan="1" rowSpan="1" width="auto">周三</td><td colSpan="1" rowSpan="1" width="auto">19:00-20:30</td><td colSpan="1" rowSpan="1" width="auto">全场10片</td></tr></tbody></table><p><br></p>',
    transportationRoutes: null,
    operationTime: '10：00-22：00',
    createTime: 1742026405000,
    facilities: null,
    fields: null,
    campus: null,
  },
];
