name: publish to npm and cdn

on:
  push:
    branches:
      - master
    paths: 
       - 'package.json'
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: node --version
      - run: yarn
      - run: yarn build
      - name: publish
        run: |
          yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}